--ALTER SESSION SET CURRENT_SCHEMA=sankhya;
WITH 
CTE_NOTA_SERVICO AS (
    SELECT *
    FROM  VM_NOTA_SERVICO
       
),
CTE_NOTA_PRODUTO AS (
    SELECT * 
    FROM VM_NOTA_PRODUTO
)
SELECT * 
FROM (
    SELECT 
 CAB.DTENTSAI AS DATA_SAIDA, CAB.DTNEG AS DATA_NEGOCIACAO, CAB.DTFATUR AS DATA_FATURAMENTO,
        EMPRESA, CAB.NOMEFANTASIA, CAB.CID_ORIGEM, CAB.UF_ORIGEM,
        CAB.NUNOTA, CAB.NOTA_FISCAL, CAB.PEDIDO, CAB.AD_NUINVOICE, CAB.PARCEIRO, CAB.NOMEPARC, CAB.CODPARCMATRIZ,
        CAB.NOMEPARCMATRIZ, CAB.CODNAT, CAB.DESCRNAT, CAB.CODCTACTB, CAB.DESCRCTA, COD_VENDEDOR, VENDEDOR,
        CAB.TOP, CAB.DESC_TOP, CAB.SEQUENCIA, CAB.CODPROD, CAB.DESCRPROD, CAB.ALIQICMS, CAB.BASEICMS, CAB.VLRICMS,
        CAB.ALIQIPI,CAB.VLRIPI,CAB.BASEIPI,CAB.BASESUBSTIT,CAB.VLRSUBST,CAB.CODCFO,CAB.QTDNEG,CAB.NCM,CAB.VLRUNIT,CAB.VLR_NF,CAB.VALOR_ITEM,
        VALOR_ITEM_IMPOSTOS,CAB.VLRMOEDA,CAB.VLRISS,CAB.VLRDESC,CAB.CODGRUPOPROD,CAB.DESCRGRUPOPROD,CAB.MARCA,NOMEREG,
        GRUPO,CAB.TIPMOV,CAB.MES_ANO,VLRTOTITE,CAB.VLRDESCTOT, CAB.VLRDESCTOTITEM, CAB.VLRDESCTOTITEMMOE,DESCRCENCUS,
        ICMS,ST,IPI,ISS,PIS,COFINS,FGCOLOR,TipoDesconto,NOMECID,DESCRICAO,UF,NetPrice,CODTIPPARC,DESCRTIPPARC,
        VLRDIFALDEST,VLRFCP,BASEDIFAL,BASEFCP,IDALIQICMS,MARGLUCRO,ALIQSUBTRIB,PERCSTFCPINT,CGC_CPF,TIPPESSOA,GERENTE,CTACONCIL,
        PLA_CONCIL.DESCRCTA DESCCTACONCIL, CAB.CODCENCUS, CAB.CODAGRUPPROD, CAB.DESCRAGRUPPROD,
        TABPRECO, CAB.DTPEDIDO, cab.codtipvenda, cab.DESCRTIPVENDA,
        CASE WHEN ((CAB.CODNAT = 1010101) and CAB.VLR_NF > 0) THEN
           round(((nvl(CAB.VALOR_ITEM_IMPOSTOS,0) / nvl(CAB.VLR_NF,1)) * (nvl(CAB_ROY.VLRNOTA,0) + nvl(CAB_TXP.VLRNOTA,0))),2) 
           ELSE 0 
        END VLR_SERV,
        CAB_ROY.NUNOTA NUNOTA_ROYALTIES, CAB_ROY.DTENTSAI DTENTSAI_ROYALTIES, CAB_ROY.VLRNOTA VLRNOTA_ROYALTIES,
        CAB_TXP.NUNOTA NUNOTA_TXPUBLIC, CAB_TXP.DTENTSAI DTENTSAI_TXPUBLIC, CAB_TXP.VLRNOTA VLRNOTA_TXPUBLIC,
        
        RB.RB_TOTAL, RB.RB_PRODUTOS, RB.RB_SERVICOS
    FROM 
        VM_NOTAS_FATURADAS CAB
    JOIN 
        tgfcab c ON c.nunota = cab.nunota 
        AND (C.STATUSNFE = 'A' OR C.STATUSNFSE = 'A') 
        AND C.TIPMOV = 'V'
    LEFT JOIN 
        TCBPLA PLA_CONCIL ON PLA_CONCIL.CODCTACTB = CAB.CTACONCIL
    LEFT JOIN 
        CTE_NOTA_SERVICO TOT_TX ON TOT_TX.NotaOrig = CAB.PEDIDO
    LEFT JOIN 
        CTE_NOTA_PRODUTO TB_CO ON CAB.PEDIDO = TB_CO.NUNOTA_PROD
     LEFT JOIN TGFCAB CAB_ROY ON CAB_ROY.AD_NUNOTA = CAB.PEDIDO AND CAB_ROY.TIPMOV = 'V' and CAB_ROY.Codtipoper = 3205 and TO_CHAR(CAB_ROY.DTENTSAI, 'mm/yyyy') = TO_CHAR(TB_CO.DT_SERVICO, 'mm/yyyy')
     LEFT JOIN TGFCAB CAB_TXP ON CAB_TXP.AD_NUNOTA = CAB.PEDIDO AND CAB_TXP.TIPMOV = 'V' and CAB_TXP.Codtipoper = 3238 and TO_CHAR(CAB_TXP.DTENTSAI, 'mm/yyyy') = TO_CHAR(TB_CO.DT_SERVICO, 'mm/yyyy')
       
    LEFT JOIN RECEITA_BRUTA_PED_SKU RB on RB.NUNOTA_PEDIDO = CAB.PEDIDO AND RB.CODPROD = CAB.CODPROD 
) CAB


where CAB.DATA_SAIDA BETWEEN :DTINI AND :DTFIM
 AND (CAB.EMPRESA = :CODEMP OR :CODEMP IS NULL)
 AND (CAB.CODTIPPARC =:CODTIPPARC OR :CODTIPPARC IS NULL)
 AND (CAB.CODCENCUS =:CODCENCUS OR :CODCENCUS IS NULL)
 AND (CAB.CODNAT =:CODNAT OR :CODNAT IS NULL)
 AND (CAB.PARCEIRO =:CODPARC OR :CODPARC IS NULL)
 AND (CAB.CODPARCMATRIZ =:CODPARCMATRIZ OR :CODPARCMATRIZ IS NULL)
 AND (CAB.CODPROD =:CODPROD OR :CODPROD IS NULL)
 AND (CAB.NUNOTA =:NUNOTA OR :NUNOTA IS NULL)
 AND (CAB.PEDIDO =:PEDIDO OR :PEDIDO IS NULL)
