--ALTER SESSION SET CURRENT_SCHEMA=sankhya;

SELECT * FROM (
        select 
        CAB.DTENTSAI AS DATA_SAIDA, CAB.DTNEG AS DATA_NEGOCIACAO, CAB.DTFATUR AS DATA_FATURAMENTO,
        EMPRESA, CAB.NOMEFANTASIA, CAB.CID_ORIGEM, CAB.UF_ORIGEM,
        CAB.NUNOTA, CAB.NOTA_FISCAL, CAB.PEDIDO, CAB.AD_NUINVOICE, CAB.PARCEIRO, CAB.NOMEPARC, CAB.CODPARCMATRIZ,
        CAB.NOMEPARCMATRIZ, CAB.CODNAT, CAB.DESCRNAT, CAB.CODCTACTB, CAB.DESCRCTA, COD_VENDEDOR, VENDEDOR,
        CAB.TOP, CAB.DESC_TOP, CAB.SEQUENCIA, CAB.CODPROD, CAB.DESCRPROD, CAB.ALIQICMS, CAB.BASEICMS, CAB.VLRICMS,
        CAB.ALIQIPI,CAB.VLRIPI,CAB.BASEIPI,CAB.BASESUBSTIT,CAB.VLRSUBST,CAB.CODCFO,CAB.QTDNEG,CAB.NCM,CAB.VLRUNIT,CAB.VLR_NF,CAB.VALOR_ITEM,
        VALOR_ITEM_IMPOSTOS,CAB.VLRMOEDA,CAB.VLRISS,CAB.VLRDESC,CAB.CODGRUPOPROD,CAB.DESCRGRUPOPROD,CAB.MARCA,NOMEREG,
        GRUPO,CAB.TIPMOV,CAB.MES_ANO,VLRTOTITE,CAB.VLRDESCTOT, CAB.VLRDESCTOTITEM, CAB.VLRDESCTOTITEMMOE,DESCRCENCUS,
        ICMS,ST,IPI,ISS,PIS,COFINS,FGCOLOR,TipoDesconto,NOMECID,DESCRICAO,UF,NetPrice,CODTIPPARC,DESCRTIPPARC,
        VLRDIFALDEST,VLRFCP,BASEDIFAL,BASEFCP,IDALIQICMS,MARGLUCRO,ALIQSUBTRIB,PERCSTFCPINT,CGC_CPF,TIPPESSOA,GERENTE,CTACONCIL,
        PLA_CONCIL.DESCRCTA DESCCTACONCIL, CAB.CODCENCUS, CAB.CODAGRUPPROD, CAB.DESCRAGRUPPROD,
        TABPRECO, CAB.DTPEDIDO, cab.codtipvenda, cab.DESCRTIPVENDA,
        CASE WHEN ((CAB.CODNAT = 1010101) and CAB.VLR_NF > 0) THEN round(((nvl(CAB.VALOR_ITEM_IMPOSTOS,0) / nvl(CAB.VLR_NF,1)) * (nvl(CAB_ROY.VLRNOTA,0) + nvl(CAB_TXP.VLRNOTA,0))),2) ELSE 0 END VLR_SERV,
        CAB_ROY.NUNOTA NUNOTA_ROYALTIES, CAB_ROY.DTENTSAI DTENTSAI_ROYALTIES, CAB_ROY.VLRNOTA VLRNOTA_ROYALTIES,
        CAB_TXP.NUNOTA NUNOTA_TXPUBLIC, CAB_TXP.DTENTSAI DTENTSAI_TXPUBLIC, CAB_TXP.VLRNOTA VLRNOTA_TXPUBLIC,
        RB.RB_TOTAL, RB.RB_PRODUTOS, RB.RB_SERVICOS

        FROM V_NFFATUR_ITENS_BOLETIM_DIARIO CAB
        JOIN tgfcab c on c.nunota = cab.nunota AND (C.STATUSNFE = 'A' OR C.STATUSNFSE = 'A') AND C.TIPMOV = 'V'/*Ajustado aqui por Daniel Campos na data 20/03/2025*/
        LEFT  JOIN TCBPLA PLA_CONCIL ON PLA_CONCIL.CODCTACTB = CAB.CTACONCIL
        LEFT JOIN (select NotaOrig, Serv, sum(qtdneg) ITE_QTDNEG, Serv / sum(qtdneg) TOT_ITEM_SERV, DTENTSAI_TX
                   from(
                        select cab_tx.ad_nunota NotaOrig, SUM(cab_tx.vlrnota) Serv, 
                        TO_CHAR(cab_tx.DTENTSAI, 'mm/yyyy') DTENTSAI_TX
                        from tgfcab cab_tx
                        where cab_tx.CODTIPOPER IN (3205,3238)
                        AND cab_tx.STATUSNOTA = 'L'
                        AND (cab_tx.statusnfe = 'A' or cab_tx.statusnfse = 'A')
                        AND cab_tx.TIPMOV = 'V'
                        group by cab_tx.ad_nunota, TO_CHAR(cab_tx.DTENTSAI, 'mm/yyyy')
                    ) cab_tx
                    left join tgfite ite on ite.nunota = cab_tx.NotaOrig 
                    group by NotaOrig, Serv, DTENTSAI_TX
        ) TOT_TX ON TOT_TX.NotaOrig = CAB.PEDIDO and TOT_TX.DTENTSAI_TX = TO_CHAR(CAB.DTPEDIDO,'mm/yyyy')
        LEFT JOIN TGFCAB CAB_ROY ON CAB_ROY.AD_NUNOTA = CAB.PEDIDO AND CAB_ROY.TIPMOV = 'V' and CAB_ROY.Codtipoper = 3205 and TO_CHAR(CAB_ROY.DTENTSAI, 'mm/yyyy') = TO_CHAR(CAB.DTPEDIDO,'mm/yyyy')
        LEFT JOIN TGFCAB CAB_TXP ON CAB_TXP.AD_NUNOTA = CAB.PEDIDO AND CAB_TXP.TIPMOV = 'V' and CAB_TXP.Codtipoper = 3238 and TO_CHAR(CAB_TXP.DTENTSAI, 'mm/yyyy') = TO_CHAR(CAB.DTPEDIDO,'mm/yyyy')
        LEFT JOIN RECEITA_BRUTA_PED_SKU RB on RB.NUNOTA_PEDIDO = CAB.NUNOTA AND RB.CODPROD = CAB.CODPROD  


        UNION ALL

        select 
        TB_CO.DT_SERVICO AS DATA_SAIDA, CAB.DTNEG AS DATA_NEGOCIACAO, CAB.DTFATUR AS DATA_FATURAMENTO,
        EMPRESA, CAB.NOMEFANTASIA, CAB.CID_ORIGEM, CAB.UF_ORIGEM,
        CAB.NUNOTA, CAB.NOTA_FISCAL, CAB.PEDIDO, CAB.AD_NUINVOICE, CAB.PARCEIRO, CAB.NOMEPARC, CAB.CODPARCMATRIZ,
        CAB.NOMEPARCMATRIZ, CAB.CODNAT, CAB.DESCRNAT, CAB.CODCTACTB, CAB.DESCRCTA, COD_VENDEDOR, VENDEDOR,
        CAB.TOP, CAB.DESC_TOP, CAB.SEQUENCIA, CAB.CODPROD, CAB.DESCRPROD, 0 ALIQICMS, 0 BASEICMS, 0 VLRICMS,
        0 ALIQIPI,0 VLRIPI, 0 BASEIPI, 0 BASESUBSTIT, 0 VLRSUBST,CAB.CODCFO, 0 QTDNEG,CAB.NCM, 0 VLRUNIT, 0 VLR_NF,0 VALOR_ITEM,
        0 VALOR_ITEM_IMPOSTOS,0 VLRMOEDA, 0 VLRISS,0 VLRDESC,CAB.CODGRUPOPROD,CAB.DESCRGRUPOPROD,CAB.MARCA,NOMEREG,
        GRUPO,CAB.TIPMOV,CAB.MES_ANO, 0 VLRTOTITE, 0 VLRDESCTOT, 0 VLRDESCTOTITEM, 0 VLRDESCTOTITEMMOE,DESCRCENCUS,
        0 ICMS,0 ST,0 IPI,0 ISS,0 PIS,0 COFINS,FGCOLOR,TipoDesconto,NOMECID,DESCRICAO,UF,0 NetPrice,CODTIPPARC,DESCRTIPPARC,
        0 VLRDIFALDEST,0 VLRFCP,0 BASEDIFAL,0 BASEFCP,0 IDALIQICMS,0 MARGLUCRO,0 ALIQSUBTRIB,0 PERCSTFCPINT,CGC_CPF,TIPPESSOA,GERENTE,CTACONCIL,
        PLA_CONCIL.DESCRCTA DESCCTACONCIL, CAB.CODCENCUS, CAB.CODAGRUPPROD, CAB.DESCRAGRUPPROD,
        TABPRECO, CAB.DTPEDIDO, cab.codtipvenda, cab.DESCRTIPVENDA,
        CASE WHEN ((CAB.CODNAT = 1010101) and CAB.VLR_NF > 0) THEN round(((nvl(CAB.VALOR_ITEM_IMPOSTOS,0) / nvl(CAB.VLR_NF,1)) * (nvl(CAB_ROY.VLRNOTA,0) + nvl(CAB_TXP.VLRNOTA,0))),2) ELSE 0 END VLR_SERV,
        CAB_ROY.NUNOTA NUNOTA_ROYALTIES, CAB_ROY.DTENTSAI DTENTSAI_ROYALTIES, CAB_ROY.VLRNOTA VLRNOTA_ROYALTIES,
        CAB_TXP.NUNOTA NUNOTA_TXPUBLIC, CAB_TXP.DTENTSAI DTENTSAI_TXPUBLIC, CAB_TXP.VLRNOTA VLRNOTA_TXPUBLIC, 
        RB.RB_TOTAL, RB.RB_PRODUTOS, RB.RB_SERVICOS        
        FROM V_NFFATUR_ITENS_BOLETIM_DIARIO CAB
        JOIN tgfcab c on c.nunota = cab.nunota AND (C.STATUSNFE = 'A' OR C.STATUSNFSE = 'A') AND C.TIPMOV = 'V'/*Ajustado aqui por Daniel Campos na data 20/03/2025*/
        LEFT  JOIN TCBPLA PLA_CONCIL ON PLA_CONCIL.CODCTACTB = CAB.CTACONCIL
        INNER JOIN
                (select
                  NUNOTA_PROD, SERV, sum(qtdneg) ITE_QTDNEG,
                  SERV / sum(qtdneg) VALOR_SERV_CO, DT_SERVICO
                  from(
                          select  A.AD_NUNOTA NUNOTA_PROD, sum(A.VLRNOTA) SERV,
                          A.DTENTSAI DT_SERVICO
                          from TGFCAB A
                          LEFT JOIN TGFCAB B ON A.AD_NUNOTA = B.NUNOTA
                          where A.CODTIPOPER IN (3205,3238)
                          AND A.STATUSNOTA = 'L'
                          AND (A.statusnfe = 'A' or A.statusnfse = 'A')
                          AND A.TIPMOV = 'V'
                          and TO_CHAR(B.DTENTSAI, 'mm/yyyy') <> TO_CHAR(A.DTENTSAI, 'mm/yyyy')
                          group by A.AD_NUNOTA, A.DTENTSAI
                       ) TOT_CO
                  LEFT JOIN tgfite ite on ite.nunota = TOT_CO.NUNOTA_PROD
                  GROUP BY NUNOTA_PROD, SERV, DT_SERVICO
                  )TB_CO on CAB.PEDIDO = TB_CO.NUNOTA_PROD
        LEFT JOIN TGFCAB CAB_ROY ON CAB_ROY.AD_NUNOTA = CAB.PEDIDO AND CAB_ROY.TIPMOV = 'V' and CAB_ROY.Codtipoper = 3205 and TO_CHAR(CAB_ROY.DTENTSAI, 'mm/yyyy') = TO_CHAR(TB_CO.DT_SERVICO, 'mm/yyyy')
        LEFT JOIN TGFCAB CAB_TXP ON CAB_TXP.AD_NUNOTA = CAB.PEDIDO AND CAB_TXP.TIPMOV = 'V' and CAB_TXP.Codtipoper = 3238 and TO_CHAR(CAB_TXP.DTENTSAI, 'mm/yyyy') = TO_CHAR(TB_CO.DT_SERVICO, 'mm/yyyy')
        LEFT JOIN RECEITA_BRUTA_PED_SKU RB on RB.NUNOTA_PEDIDO = CAB.NUNOTA AND RB.CODPROD = CAB.CODPROD 
) CAB
WHERE CAB.NUNOTA = 822662
/* WHERE CAB.DATA_SAIDA BETWEEN :DTINI AND :DTFIM
 AND (CAB.EMPRESA = :CODEMP OR :CODEMP IS NULL)
 AND (CAB.CODTIPPARC =:CODTIPPARC OR :CODTIPPARC IS NULL)
 AND (CAB.CODCENCUS =:CODCENCUS OR :CODCENCUS IS NULL)
 AND (CAB.CODNAT =:CODNAT OR :CODNAT IS NULL)
 AND (CAB.PARCEIRO =:CODPARC OR :CODPARC IS NULL)
 AND (CAB.CODPARCMATRIZ =:CODPARCMATRIZ OR :CODPARCMATRIZ IS NULL)
 AND (CAB.CODPROD =:CODPROD OR :CODPROD IS NULL)  */
   
ORDER BY DATA_SAIDA, NOTA_FISCAL
