SELECT * FROM (
        SELECT/*Vinicius passou aqui*/
        CAB.DTENTSAI AS DATA_SAIDA, CAB.DTNEG AS DATA_NEGOCIACAO, CAB.DTFATUR AS DATA_FATURAMENTO,
        EMPRESA, CAB.NOMEFANTASIA, CAB.CID_ORIGEM, CAB.UF_ORIGEM,
        CAB.NUNOTA, CAB.NOTA_FISCAL, CAB.PEDIDO, CAB.AD_NUINVOICE, CAB.PARCEIRO, CAB.NOMEPARC, CAB.CODPARCMATRIZ,
        CAB.NOMEPARCMATRIZ, CAB.CODNAT, CAB.DESCRNAT, CAB.CODCTACTB, CAB.DESCRCTA, COD_VENDEDOR, VENDEDOR,
        CAB.TOP, CAB.DESC_TOP, CAB.SEQUENCIA, CAB.CODPROD, CAB.DESCRPROD,
        /*Adicionado por Bruno Vieira, cálculo do custo médio do relatório Kardex*/
        NVL((SELECT AVG(TGFCUS.CUSMEDICM)
             FROM TGFCUS
             WHERE CODPROD = CAB.CODPROD
               AND CODEMP  = CAB.EMPRESA
               AND DTATUAL = (SELECT MAX(DTATUAL)
                              FROM TGFCUS
                              WHERE CODPROD = CAB.CODPROD
                                AND CODEMP  = CAB.EMPRESA
                                AND DTATUAL <= CAB.DTENTSAI)), 0) AS CUSTO_MED_COM,
        NVL((SELECT AVG(TGFCUS.CUSSEMICM)
             FROM TGFCUS
             WHERE CODPROD = CAB.CODPROD
               AND CODEMP  = CAB.EMPRESA
               AND DTATUAL = (SELECT MAX(DTATUAL)
                              FROM TGFCUS
                              WHERE CODPROD = CAB.CODPROD
                                AND CODEMP  = CAB.EMPRESA
                                AND DTATUAL  <=  CAB.DTENTSAI)), 0) AS CUSTO_MED_SEM,
        CAB.ALIQICMS, CAB.BASEICMS, CAB.VLRICMS,
        CAB.ALIQIPI, CAB.VLRIPI, CAB.BASEIPI, CAB.BASESUBSTIT, CAB.VLRSUBST, CAB.CODCFO, CAB.QTDNEG, CAB.NCM, CAB.VLRUNIT, CAB.VLR_NF, VLRTOTITE AS VALOR_ITEM,
        VALOR_ITEM_IMPOSTOS, CAB.VLRMOEDA, CAB.VLRISS, CAB.VLRDESC, CAB.CODGRUPOPROD, CAB.DESCRGRUPOPROD, CAB.MARCA, NOMEREG,
        GRUPO, CAB.TIPMOV, CAB.MES_ANO, VLRTOTITE, CAB.VLRDESCTOT, CAB.VLRDESCTOTITEM, CAB.VLRDESCTOTITEMMOE, DESCRCENCUS,
        ICMS, ST, IPI, ISS, PIS, COFINS, FGCOLOR, TipoDesconto, NOMECID, DESCRICAO, UF, NetPrice, CODTIPPARC, DESCRTIPPARC,
        VLRDIFALDEST, VLRFCP, BASEDIFAL, BASEFCP, IDALIQICMS, MARGLUCRO, ALIQSUBTRIB, PERCSTFCPINT, CGC_CPF, TIPPESSOA, GERENTE, CTACONCIL,
        PLA_CONCIL.DESCRCTA DESCCTACONCIL, CAB.CODCENCUS, CAB.CODAGRUPPROD, CAB.DESCRAGRUPPROD,
        TABPRECO, CAB.DTPEDIDO, CAB.CODTIPVENDA, CAB.DESCRTIPVENDA,
        CASE WHEN ((CAB.CODNAT = 1010101) AND CAB.VLR_NF > 0)
        THEN ROUND(NVL(CAB.VLRUNIT, 0) * (NVL(CAB.VLRDESCTOT, 0) / NULLIF(CAB.VLR_NF, 1)), 2)
        ELSE 0
        END AS DESCONTO_ITEM_SERVICO,
        CASE WHEN ((CAB.CODNAT = 1010101) AND CAB.VLR_NF > 0) THEN ROUND(((NVL(CAB.VALOR_ITEM_IMPOSTOS, 0) / NVL(CAB.VLR_NF, 1)) * (NVL(CAB_ROY.VLRNOTA, 0) + NVL(CAB_TXP.VLRNOTA, 0))), 2) ELSE 0 END VLR_SERV,
        /*Bruno Vieira - Cálculo do valor de desconto para o serviço com base no percentual de desconto do produto*/
        CASE 
        WHEN ((NVL(CAB.VALOR_ITEM_IMPOSTOS, 0) / NULLIF(CAB.VLR_NF, 1)) * (NVL(CAB_ROY.VLRNOTA, 0) + NVL(CAB_TXP.VLRNOTA, 0))) > 0
             AND (VLRDESC) > 0 AND (VLRTOTITE) > 0
        THEN ROUND(
            (VLRDESC / NULLIF(VLRTOTITE, 0)) 
            * ((NVL(CAB.VALOR_ITEM_IMPOSTOS, 0) / NULLIF(CAB.VLR_NF, 1)) * (NVL(CAB_ROY.VLRNOTA, 0) + NVL(CAB_TXP.VLRNOTA, 0)))
        , 2)
        ELSE 0 
        END AS VLR_DESC_SERV,
        /* Bruno Vieira - Soma do valor do serviço com o valor de desconto*/
        ROUND(
        NVL((NVL(CAB.VALOR_ITEM_IMPOSTOS, 0) / NULLIF(CAB.VLR_NF, 1)) * 
            (NVL(CAB_ROY.VLRNOTA, 0) + NVL(CAB_TXP.VLRNOTA, 0)), 0)
        +
        CASE 
            WHEN ((NVL(CAB.VALOR_ITEM_IMPOSTOS, 0) / NULLIF(CAB.VLR_NF, 1)) * 
                  (NVL(CAB_ROY.VLRNOTA, 0) + NVL(CAB_TXP.VLRNOTA, 0))) > 0
                 AND NVL(VLRDESC, 0) > 0 AND NVL(VLRTOTITE, 0) > 0
            THEN ROUND(
                (VLRDESC / NULLIF(VLRTOTITE, 0)) *
                ((NVL(CAB.VALOR_ITEM_IMPOSTOS, 0) / NULLIF(CAB.VLR_NF, 1)) *
                 (NVL(CAB_ROY.VLRNOTA, 0) + NVL(CAB_TXP.VLRNOTA, 0)))
            , 2)
            ELSE 0 
        END
        , 2) AS VLR_TOTAL_SERVICOS,
        CAB_ROY.NUNOTA NUNOTA_ROYALTIES, CAB_ROY.DTENTSAI DTENTSAI_ROYALTIES, CAB_ROY.VLRNOTA VLRNOTA_ROYALTIES,
        CAB_TXP.NUNOTA NUNOTA_TXPUBLIC, CAB_TXP.DTENTSAI DTENTSAI_TXPUBLIC, CAB_TXP.VLRNOTA VLRNOTA_TXPUBLIC,
        RB.RB_TOTAL, RB.RB_SERVICOS, RB.RB_PRODUTOS


        FROM V_NFFATUR_ITENS_BOLETIM_DIARIO CAB
        JOIN TGFCAB C ON C.NUNOTA = CAB.NUNOTA AND (C.STATUSNFE = 'A' OR C.STATUSNFSE = 'A') AND C.TIPMOV = 'V'
        LEFT JOIN TCBPLA PLA_CONCIL ON PLA_CONCIL.CODCTACTB = CAB.CTACONCIL
        LEFT JOIN (
                  SELECT NotaOrig, DTENTSAI_TX
                  FROM (
                          SELECT
                          CAB_TX.AD_NUNOTAORIG NotaOrig,
                          TO_CHAR(CAB_TX.DTENTSAI, 'mm/yyyy') DTENTSAI_TX
                      FROM TGFCAB CAB_TX
                      WHERE
                          CAB_TX.CODTIPOPER IN (3205, 3238)
                          AND CAB_TX.STATUSNOTA = 'L'
                          AND (CAB_TX.STATUSNFE = 'A' OR CAB_TX.STATUSNFSE = 'A')
                          AND CAB_TX.TIPMOV = 'V'
                      GROUP BY CAB_TX.AD_NUNOTAORIG, TO_CHAR(CAB_TX.DTENTSAI, 'mm/yyyy')
                  ) CAB_TX
                  LEFT JOIN TGFITE ITE ON ITE.NUNOTA = CAB_TX.NotaOrig
                  GROUP BY NotaOrig, DTENTSAI_TX
          ) TOT_TX ON TOT_TX.NotaOrig = CAB.NUNOTA AND TOT_TX.DTENTSAI_TX = TO_CHAR(CAB.DTFATUR, 'mm/yyyy')
          LEFT JOIN TGFCAB CAB_ROY ON CAB_ROY.AD_NUNOTAORIG = CAB.NUNOTA AND CAB_ROY.TIPMOV = 'V' AND CAB_ROY.CODTIPOPER = 3205 AND TO_CHAR(CAB_ROY.DTENTSAI, 'mm/yyyy') = TO_CHAR(CAB.DTFATUR, 'mm/yyyy') AND (CAB_ROY.AD_NFCANCELADA = 'N' OR CAB_ROY.AD_NFCANCELADA IS NULL)
          LEFT JOIN TGFCAB CAB_TXP ON CAB_TXP.AD_NUNOTAORIG = CAB.NUNOTA AND CAB_TXP.TIPMOV = 'V' AND CAB_TXP.CODTIPOPER = 3238 AND TO_CHAR(CAB_TXP.DTENTSAI, 'mm/yyyy') = TO_CHAR(CAB.DTFATUR, 'mm/yyyy')  AND (CAB_TXP.AD_NFCANCELADA = 'N' OR CAB_TXP.AD_NFCANCELADA IS NULL)
          LEFT JOIN V_RECEITA_BRUTA_NF_SKU RB ON RB.NUNOTA = CAB.NUNOTA AND RB.CODPROD = CAB.CODPROD AND RB.SEQUENCIA= CAB.SEQUENCIA 

        UNION ALL

        -- Segunda parte da consulta
        SELECT
        TB_CO.DT_SERVICO AS DATA_SAIDA, CAB.DTNEG AS DATA_NEGOCIACAO, CAB.DTFATUR AS DATA_FATURAMENTO,
        EMPRESA, CAB.NOMEFANTASIA, CAB.CID_ORIGEM, CAB.UF_ORIGEM,
        CAB.NUNOTA, CAB.NOTA_FISCAL, CAB.PEDIDO, CAB.AD_NUINVOICE, CAB.PARCEIRO, CAB.NOMEPARC, CAB.CODPARCMATRIZ,
        CAB.NOMEPARCMATRIZ, CAB.CODNAT, CAB.DESCRNAT, CAB.CODCTACTB, CAB.DESCRCTA, COD_VENDEDOR, VENDEDOR,
        CAB.TOP, CAB.DESC_TOP, CAB.SEQUENCIA, CAB.CODPROD, CAB.DESCRPROD, 0 AS CUSTO_MED_COM, 0 AS CUSTO_MED_SEM,
        0 ALIQICMS, 0 BASEICMS, 0 VLRICMS,
        0 ALIQIPI, 0 VLRIPI, 0 BASEIPI, 0 BASESUBSTIT, 0 VLRSUBST, CAB.CODCFO, 0 QTDNEG, CAB.NCM, 0 VLRUNIT, 0 VLR_NF, 0 VALOR_ITEM,
        0 VALOR_ITEM_IMPOSTOS, 0 VLRMOEDA, 0 VLRISS, 0 VLRDESC, CAB.CODGRUPOPROD, CAB.DESCRGRUPOPROD, CAB.MARCA, NOMEREG,
        GRUPO, CAB.TIPMOV, CAB.MES_ANO, 0 VLRTOTITE, 0 VLRDESCTOT, 0 VLRDESCTOTITEM, 0 VLRDESCTOTITEMMOE, DESCRCENCUS,
        0 ICMS, 0 ST, 0 IPI, 0 ISS, 0 PIS, 0 COFINS, FGCOLOR, TipoDesconto, NOMECID, DESCRICAO, UF, 0 NetPrice, CODTIPPARC, DESCRTIPPARC,
        0 VLRDIFALDEST, 0 VLRFCP, 0 BASEDIFAL, 0 BASEFCP, 0 IDALIQICMS, 0 MARGLUCRO, 0 ALIQSUBTRIB, 0 PERCSTFCPINT, CGC_CPF, TIPPESSOA, GERENTE, CTACONCIL,
        PLA_CONCIL.DESCRCTA DESCCTACONCIL, CAB.CODCENCUS, CAB.CODAGRUPPROD, CAB.DESCRAGRUPPROD,
        TABPRECO, CAB.DTPEDIDO, CAB.CODTIPVENDA, CAB.DESCRTIPVENDA, 0 DESCONTO_ITEM_SERVICO,
        CASE WHEN ((CAB.CODNAT = 1010101) AND CAB.VLR_NF > 0) THEN ROUND(((NVL(CAB.VALOR_ITEM_IMPOSTOS, 0) / NVL(CAB.VLR_NF, 1)) * (NVL(CAB_ROY.VLRNOTA, 0) + NVL(CAB_TXP.VLRNOTA, 0))), 2) ELSE 0 END VLR_SERV,
        0 VLR_DESC_SERV, 0 VLR_TOTAL_SERVICOS,
        CAB_ROY.NUNOTA NUNOTA_ROYALTIES, CAB_ROY.DTENTSAI DTENTSAI_ROYALTIES, CAB_ROY.VLRNOTA VLRNOTA_ROYALTIES,
        CAB_TXP.NUNOTA NUNOTA_TXPUBLIC, CAB_TXP.DTENTSAI DTENTSAI_TXPUBLIC, CAB_TXP.VLRNOTA VLRNOTA_TXPUBLIC,
        RB.RB_TOTAL, RB.RB_SERVICOS, RB.RB_PRODUTOS

        FROM V_NFFATUR_ITENS_BOLETIM_DIARIO CAB
        JOIN TGFCAB C ON C.NUNOTA = CAB.NUNOTA AND (C.STATUSNFE = 'A' OR C.STATUSNFSE = 'A') AND C.TIPMOV = 'V'
        LEFT JOIN TCBPLA PLA_CONCIL ON PLA_CONCIL.CODCTACTB = CAB.CTACONCIL
        INNER JOIN (
            SELECT NUNOTA_PROD, DT_SERVICO
            FROM (
              SELECT A.AD_NUNOTAORIG NUNOTA_PROD, A.DTENTSAI DT_SERVICO
              FROM TGFCAB A
              LEFT JOIN TGFCAB B ON A.AD_NUNOTA = B.NUNOTA
              WHERE A.CODTIPOPER IN (3205, 3238)
                AND A.STATUSNOTA = 'L'
                AND (A.STATUSNFE = 'A' OR A.STATUSNFSE = 'A')
                AND A.TIPMOV = 'V'
                AND TO_CHAR(B.DTENTSAI, 'mm/yyyy') <> TO_CHAR(A.DTENTSAI, 'mm/yyyy')
              GROUP BY A.AD_NUNOTAORIG, A.DTENTSAI
            ) TOT_CO
              LEFT JOIN TGFITE ITE ON ITE.NUNOTA = TOT_CO.NUNOTA_PROD
              GROUP BY NUNOTA_PROD, DT_SERVICO
           ) TB_CO
                ON TB_CO.NUNOTA_PROD = CAB.NUNOTA
        LEFT JOIN TGFCAB CAB_ROY ON CAB_ROY.AD_NUNOTAORIG = CAB.NUNOTA AND CAB_ROY.TIPMOV = 'V' AND CAB_ROY.CODTIPOPER = 3205 AND TO_CHAR(CAB_ROY.DTENTSAI, 'mm/yyyy') = TO_CHAR(TB_CO.DT_SERVICO, 'mm/yyyy') AND (CAB_ROY.AD_NFCANCELADA = 'N' OR CAB_ROY.AD_NFCANCELADA IS NULL)
        LEFT JOIN TGFCAB CAB_TXP ON CAB_TXP.AD_NUNOTAORIG = CAB.NUNOTA AND CAB_TXP.TIPMOV = 'V' AND CAB_TXP.CODTIPOPER = 3238 AND TO_CHAR(CAB_TXP.DTENTSAI, 'mm/yyyy') = TO_CHAR(TB_CO.DT_SERVICO, 'mm/yyyy') AND (CAB_TXP.AD_NFCANCELADA = 'N' OR CAB_TXP.AD_NFCANCELADA IS NULL)
        LEFT JOIN V_RECEITA_BRUTA_PED_SKU RB ON RB.NUNOTA_PEDIDO = CAB.PEDIDO AND RB.CODPROD = CAB.CODPROD AND RB.SEQ = CAB.SEQUENCIA

) CAB
WHERE CAB.DATA_SAIDA BETWEEN :DTINI AND :DTFIM
 AND (CAB.EMPRESA = :CODEMP OR :CODEMP IS NULL)
 AND (CAB.CODTIPPARC =:CODTIPPARC OR :CODTIPPARC IS NULL)
 AND (CAB.CODCENCUS =:CODCENCUS OR :CODCENCUS IS NULL)
 AND (CAB.CODNAT =:CODNAT OR :CODNAT IS NULL)
 AND (CAB.PARCEIRO =:CODPARC OR :CODPARC IS NULL)
 AND (CAB.CODPARCMATRIZ =:CODPARCMATRIZ OR :CODPARCMATRIZ IS NULL)
 AND (CAB.CODPROD =:CODPROD OR :CODPROD IS NULL)
 AND (CAB.PEDIDO  =:PEDIDO  OR :PEDIDO IS NULL)
 AND (CAB.NUNOTA  =:NUNOTA  OR :NUNOTA IS NULL)
ORDER BY DATA_SAIDA, NOTA_FISCAL
